name: Export pubs

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  export_pubs:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: install latex
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends texlive-latex-extra texlive-base cb2bib

    - name: run export
      run: |
        /usr/share/cb2bib/c2btools/bib2pdf my_publications.bib pubs.pdf

    - uses: actions/upload-artifact@v4
      with:
        name: pubs
        path: pubs.pdf
